// Pattern library — every signal pair the engine has scored, per persona.
// This is the evidence layer. Each persona has a different volume of indexed pairs:
// Harlow (Free, day 6) sees handfuls. Bella (Essential, day 184) sees hundreds.
// Grayson (Pro, day 247) sees thousands — but the surfaced ones are the ones that matter.

const PATTERN_LIBRARY = {
  kezia: {
    headline: "Six days of listening.",
    headlineEm: "Two patterns are already loud.",
    lede: "Your watch indexed 412 signals in your first week. Most of them are noise — that is normal, and that is what the next month is for. Two pairs have already crossed the line your body draws between coincidence and signal. Read them gently.",
    indexed: 47,
    passing: 4,
    newThisWeek: 2,
    driving: 0,
    hero: {
      id: "k-sun",
      headline: "Your resting heart rate knows it's Sunday.",
      sub: "Four Sundays out of four since you put the watch on. Same time of day, same magnitude. Sundays alone are not a finding — Sundays this consistent, on this body, are.",
      r: 0.91,
      n: 4,
      factors: [
        { name: "Sunday evening RHR", weight: 0.55, r: 0.91, color: "var(--warn)", detail: "+6 bpm above your personal baseline · 19:00–22:00 window" },
        { name: "Same-evening HRV", weight: 0.30, r: 0.68, color: "var(--brand-soft)", detail: "drops 5–9ms in the same window" },
        { name: "Subjective unease", weight: 0.15, r: 0.55, color: "var(--ink-6)", detail: "your notebook entries cluster on Sunday nights" },
      ],
      history: [
        { week: "wk-4", outcome: "near-miss" }, { week: "wk-3", outcome: "near-miss" },
        { week: "wk-2", outcome: "near-miss" }, { week: "wk-1", outcome: "near-miss" },
      ],
    },
    patterns: [
      {
        id: "k-sun", a: "Sunday evening (19:00–22:00)", b: "Resting HR ↑6 bpm",
        r: 0.91, n: 4, domain: "rhythm", recency: 1.0, novelty: 0.9, driving: false,
        colorA: "var(--ink-7)", colorB: "var(--warn)",
        sparkA: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 1.0],
        sparkB: [66, 65, 67, 66, 67, 68, 73],
        note: "the same time, every week, for every week we've watched.",
        narrative: "Of 412 signals indexed in your first week, this is the one your watch is most certain about. Sundays — every Sunday, between roughly 7pm and 10pm — your resting heart rate climbs 6 bpm above its baseline and stays there until you fall asleep. Your HRV drops in the same window. We don't yet know what's behind it. Your calendar would tell us in about 30 seconds. Until then: the pattern itself is the finding.",
        timeAxis: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
        moments: [
          { when: "Sun · wk-4", text: "RHR climbed from 67 to 73 between 19:14 and 20:02. Stayed elevated until sleep onset.", delta: "+6 bpm" },
          { when: "Sun · wk-3", text: "Same window. Same magnitude. You wrote in your notebook: 'tomorrow already.'", delta: "+6 bpm" },
          { when: "Sun · wk-2", text: "Climb began earlier, 18:44. Slightly larger. Year 11 marking weekend.", delta: "+8 bpm" },
          { when: "Sun · wk-1", text: "Most recent. Climb began 19:00 on the dot. HRV dropped 9ms.", delta: "+6 bpm" },
        ],
      },
      {
        id: "k-stand", a: "Standing >5h (school day)", b: "Same-night HRV drop",
        r: 0.74, n: 4, domain: "load", recency: 0.9, novelty: 0.4, driving: false,
        colorA: "var(--brand-soft)", colorB: "var(--flare)",
        sparkA: [4.2, 5.5, 5.8, 6.1, 5.4, 2.1, 2.8],
        sparkB: [38, 36, 34, 33, 36, 41, 40],
        note: "every long-standing day this week was followed by a hard night.",
        narrative: "Four of your seven days had >5 hours of standing time — all four were school days. All four were followed by an HRV drop of 4–8ms versus the same body's quiet days. This is one of the cleanest patterns in your file. Your notebook for those four days uses the phrase 'borrowed legs' three times.",
        timeAxis: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
        moments: [
          { when: "Wed · 4h critique session", text: "Standing 5h 48m. HRV that night: 33ms (your week-low).", delta: "−5ms" },
          { when: "Thu · play setup", text: "Standing 6h 07m. HRV that night: 32ms. Worst of the week.", delta: "−6ms" },
          { when: "Sat · home", text: "Standing 2h 11m. HRV bounced to 41ms. Body's recovery.", delta: "+8ms" },
        ],
      },
      {
        id: "k-event", a: "School events (evening)", b: "Next-day fatigue",
        r: 0.66, n: 3, domain: "load", recency: 0.8, novelty: 0.5, driving: false,
        colorA: "var(--pulse)", colorB: "var(--ink-7)",
        sparkA: [0.1, 0.2, 0.1, 0.15, 0.95, 0.1, 0.1],
        sparkB: [3.0, 2.8, 3.2, 2.9, 4.5, 4.2, 2.5],
        note: "you were already worried about wine. it might be the floor.",
        narrative: "Three school events in your file so far. Each was followed by next-day movement well below your baseline. The wine confounder is real but smaller than you'd expect — the days you drank wine without standing did not show this pattern. The standing-without-wine days did.",
        timeAxis: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
        moments: [
          { when: "Fri evening", text: "School event. 4h on feet. Glass of wine. You wrote: 'wine? event? standing?'", delta: "—" },
          { when: "Sat morning", text: "Movement: 2.5h. Your lowest non-rest day in the file.", delta: "−40%" },
        ],
      },
      {
        id: "k-baseline", a: "Sleep onset 23:30+", b: "Next-day HRV ↓",
        r: 0.59, n: 5, domain: "sleep", recency: 0.7, novelty: 0.3, driving: false,
        colorA: "var(--ink-7)", colorB: "var(--flare)",
        sparkA: [22.5, 22.8, 23.4, 23.6, 23.1, 23.8, 24.0],
        sparkB: [42, 38, 35, 33, 36, 32, 31],
        note: "well-known, but worth confirming on your body.",
        narrative: "This is a common pattern — most people will see it. We surface it because it's a strong correlation in your specific file: every night past 23:30 was followed by a same-direction drop in next-day HRV. The relationship is consistent enough to act on without needing more data.",
        timeAxis: ["d-7", "d-6", "d-5", "d-4", "d-3", "d-2", "yest"],
        moments: [
          { when: "Wed night → Thu", text: "Sleep onset 23:42. Thursday HRV: 33ms.", delta: "−5ms" },
          { when: "Fri night → Sat", text: "Sleep onset 24:11 (after the event). Saturday HRV: 32ms.", delta: "−6ms" },
        ],
      },
    ],
    discovery: [
      {
        a: "Sunday evening", b: "Resting HR ↑6 bpm",
        was: 0.78, now: 0.91,
        note: "two more Sundays of evidence pushed this from interesting to convincing.",
        when: "yesterday",
      },
      {
        a: "School event nights", b: "Next-day fatigue",
        was: 0.51, now: 0.66,
        note: "fourth event added. signature held.",
        when: "Sat",
      },
    ],
    locked: [
      {
        a: "Your Sunday spike", b: "What's actually happening Sunday evening",
        note: "Connect your calendar and we can show you whether it's marking, lesson prep, or anticipatory dread. Right now we only see the heart rate, not the cause.",
        unlock: "Calendar (Essential tier)",
      },
      {
        a: "Cycle phase", b: "HRV pattern",
        note: "If you're tracking your cycle in Apple Health, we'll align your fatigue patterns to it.",
        unlock: "Cycle data in Apple Health",
      },
    ],
  },

  simone: {
    headline: "184 days of evidence.",
    headlineEm: "Your spreadsheet was right. Here's the receipt.",
    lede: "You spent four years building a spreadsheet to find the correlation between your meeting load and your symptoms. We re-derived it from your last six months in 11 minutes. The headline number — r=0.84 — is the one you were chasing. Below it: 47 more pairs, ranked by what your body is asking you to know first.",
    indexed: 1247,
    passing: 47,
    newThisWeek: 4,
    driving: 1,
    hero: {
      id: "s-meet",
      headline: "Daily meetings >6h ↔ POTS symptoms within 48h.",
      sub: "Across 184 days. Across 12 launch weeks. Across two cycle phases. Same shape, every time. The spreadsheet number was r=0.81 — we have you at 0.84 because we have your standing time and you didn't.",
      r: 0.84,
      n: 184,
      factors: [
        { name: "Meeting hours / day", weight: 0.42, r: 0.84, color: "var(--warn)", detail: "the line is at 6h. above it your symptoms double within 48h." },
        { name: "Standing time within meetings", weight: 0.30, r: 0.71, color: "var(--brand-soft)", detail: "amplifies the meeting effect 1.6× when above 4h" },
        { name: "Cycle day 24–28", weight: 0.28, r: 0.78, color: "var(--flare)", detail: "luteal phase nearly doubles same-load impact" },
      ],
      history: [
        { week: "campaign-may", outcome: "event" }, { week: "wk-22", outcome: "near-miss" },
        { week: "wk-21", outcome: "clean" }, { week: "campaign-jun", outcome: "event" },
        { week: "wk-19", outcome: "clean" }, { week: "wk-18", outcome: "near-miss" },
        { week: "wk-17", outcome: "clean" }, { week: "campaign-aug", outcome: "near-miss" },
        { week: "wk-15", outcome: "clean" }, { week: "wk-14", outcome: "near-miss" },
        { week: "campaign-oct", outcome: "event" }, { week: "wk-12", outcome: "clean" },
        { week: "campaign-nov", outcome: "event" }, { week: "wk-10", outcome: "near-miss" },
      ],
    },
    patterns: [
      {
        id: "s-meet", a: "Daily meetings >6h", b: "POTS symptoms within 48h",
        r: 0.84, n: 184, domain: "load", recency: 1.0, novelty: 0.2, driving: true,
        colorA: "var(--warn)", colorB: "var(--flare)",
        sparkA: [4.5, 5.2, 6.1, 7.8, 8.5, 9.0, 8.5, 7.2],
        sparkB: [3.2, 3.5, 4.0, 5.2, 6.8, 7.5, 7.8, 6.5],
        note: "this is the one your spreadsheet found. we have it at 0.84.",
        narrative: "The pattern you spent four years and 1,847 spreadsheet rows building. We have 184 days of your data — and across those days, hours-of-meetings on a given day predicts POTS symptom severity 24–48 hours later with r=0.84. The threshold is sharp: below 6h/day the relationship is weak. Above 6h/day every additional hour adds 14% to next-day symptom probability. Your November campaign week is the most extreme case in the file.",
        timeAxis: ["d-7", "d-6", "d-5", "d-4", "d-3", "d-2", "d-1", "today"],
        moments: [
          { when: "Nov campaign launch", text: "8 consecutive days of >7h meetings. Symptom severity 7.8/10 on day 9. Worst stretch in your file.", delta: "+340%" },
          { when: "October hold-the-line week", text: "9.2h average. You called in sick the following Monday — the only sick day in 6 months.", delta: "+280%" },
          { when: "Recovery weeks", text: "Below 4h average. Symptoms returned to your floor (1.8/10) within 5 days, every time.", delta: "−68%" },
          { when: "This week (in progress)", text: "Tuesday hit 8.5h. Body is already responding the same way it did in November.", delta: "+38%" },
        ],
      },
      {
        id: "s-cycle", a: "Cycle day 24–28", b: "Symptom severity ↑",
        r: 0.78, n: 6, domain: "cycle", recency: 0.9, novelty: 0.4, driving: false,
        colorA: "var(--brand-soft)", colorB: "var(--flare)",
        sparkA: [0.2, 0.3, 0.4, 0.6, 0.85, 0.95, 1.0, 0.3],
        sparkB: [3.0, 3.2, 3.5, 4.0, 5.5, 6.2, 6.8, 3.2],
        note: "the 4-day window where everything else costs more.",
        narrative: "Your luteal phase (days 24–28) reliably elevates baseline symptom severity by 1.8 points. More importantly: it amplifies every other risk factor. The same 8-hour meeting day costs 1.6× as much in this window. Six full cycles of evidence.",
        timeAxis: ["d-1", "d-7", "d-14", "d-18", "d-22", "d-25", "d-27", "d+1"],
        moments: [
          { when: "Cycle 4 · day 26", text: "POTS-day during 9h launch meetings. Worst single day in 60d.", delta: "+8.1/10" },
          { when: "Cycle 5 · day 27", text: "Same load, same phase, but with the protocol. Symptoms held at 4.5/10.", delta: "−45%" },
        ],
      },
      {
        id: "s-stand", a: "Standing time in meetings", b: "Next-morning HRV drop",
        r: 0.71, n: 142, domain: "load", recency: 0.8, novelty: 0.3, driving: false,
        colorA: "var(--brand-soft)", colorB: "var(--flare)",
        sparkA: [3.0, 3.8, 4.5, 5.2, 5.8, 6.0, 5.5, 4.0],
        sparkB: [44, 41, 38, 35, 33, 32, 34, 39],
        note: "the hidden variable in the meeting equation.",
        narrative: "Two stand-up cultures (campaign reviews, stakeholder rooms) drove your standing-in-meeting time above 4h on 38 of the last 184 days. On every one of those days, your next-morning HRV came in 6–11ms lower than your average. This is what your spreadsheet was missing — Apple Watch sees it, you couldn't.",
        timeAxis: ["07:00", "10:00", "12:00", "14:00", "16:00", "18:00", "20:00", "22:00"],
        moments: [
          { when: "Stand-up day", text: "5.8h standing across 4 meetings. Next morning HRV: 33ms.", delta: "−11ms" },
          { when: "Walking 1:1 day", text: "Same total meeting hours, half the standing. Next morning HRV: 41ms.", delta: "−2ms" },
        ],
      },
      {
        id: "s-imani", a: "Late campaign weeks (you)", b: "Imani's chore load (her)",
        r: 0.69, n: 8, domain: "family", recency: 0.95, novelty: 0.7, driving: false,
        colorA: "var(--warn)", colorB: "var(--pulse)",
        sparkA: [0.3, 0.4, 0.5, 0.6, 0.85, 0.95, 0.9, 0.4],
        sparkB: [2, 2, 3, 3, 6, 7, 7, 3],
        note: "your daughter is a leading indicator of your bad weeks.",
        narrative: "An accidental finding. We watched the dishes-loaded count from your dishwasher integration and the chore-app entries on Imani's iPad — and on the weeks your meeting hours climb past 7h/day, her chore load doubles. She is filling in the gaps. She has been doing this for at least 8 of your campaign weeks. You knew and we noticed.",
        timeAxis: ["wk-1", "wk-2", "wk-3", "wk-4", "wk-5", "wk-6", "wk-7", "wk-8"],
        moments: [
          { when: "Last May campaign", text: "Imani's chore-app entries went from 2/wk to 7/wk. She added 'made dinner Thursday' herself.", delta: "+250%" },
          { when: "October", text: "Same shape. She didn't ask. She just started.", delta: "+200%" },
        ],
      },
      {
        id: "s-protocol", a: "Pre-hydration protocol", b: "POTS crash avoided",
        r: 0.82, n: 12, domain: "intervention", recency: 1.0, novelty: 0.8, driving: false,
        colorA: "var(--calm)", colorB: "var(--calm)",
        sparkA: [0, 0, 1, 1, 1, 0, 1, 1],
        sparkB: [0, 0, 1, 1, 1, 0, 1, 1],
        note: "your protocol. your evidence. it works.",
        narrative: "Of the 12 high-risk days where you ran your own pre-hydration protocol (32oz water + electrolytes between 06:00 and 09:00), 11 ended without a crash. Of the 7 high-risk days where you didn't, 5 ended in symptoms above 6/10. This is the strongest intervention pattern in your file. The protocol is yours — we just made it visible.",
        timeAxis: ["wk-1", "wk-2", "wk-3", "wk-4", "wk-5", "wk-6", "wk-7", "wk-8"],
        moments: [
          { when: "Protocol day · September 14", text: "9h meetings. Stand-ups. Cycle day 25. Symptoms held at 3.2/10.", delta: "no crash" },
          { when: "Skipped protocol · October 3", text: "Same conditions. Forgot the 9am dose. End-of-day symptoms: 7.5/10.", delta: "crash" },
        ],
      },
      {
        id: "s-sleep", a: "Sleep <6h", b: "Same-day error rate at work",
        r: 0.64, n: 89, domain: "cognition", recency: 0.6, novelty: 0.5, driving: false,
        colorA: "var(--ink-7)", colorB: "var(--warn)",
        sparkA: [7.2, 6.8, 6.4, 5.9, 5.6, 5.4, 6.1, 6.8],
        sparkB: [0.02, 0.03, 0.04, 0.06, 0.08, 0.09, 0.05, 0.03],
        note: "from your work doc revision counts. unflattering. true.",
        narrative: "We pulled this from your Google Docs revision history (with consent, your toggle, October 14). On nights you slept under 6 hours, the next-day revision-rate on your work documents climbed 60% — meaning more typos, more re-edits, more do-overs. The pattern is most extreme below 5.5h, where the rate triples.",
        timeAxis: ["d-7", "d-6", "d-5", "d-4", "d-3", "d-2", "d-1", "today"],
        moments: [
          { when: "Last Wed", text: "5.4h sleep. 14 revisions to the campaign brief by lunch. Two were word-replacements you'd already made.", delta: "3.2× baseline" },
        ],
      },
    ],
    discovery: [
      {
        a: "Pre-hydration protocol", b: "POTS crash avoided",
        was: 0.71, now: 0.82,
        note: "11th confirmation this week. your evidence base for your own intervention is now stronger than most clinical trials.",
        when: "Tuesday",
      },
      {
        a: "Imani's chore load", b: "Your campaign weeks",
        was: 0.0, now: 0.69,
        note: "this is new. we noticed it because the chore-app added export this month. you may want to know.",
        when: "Wednesday",
      },
      {
        a: "Stand-up meetings (specifically)", b: "Next-morning HRV",
        was: 0.58, now: 0.71,
        note: "30 more days of evidence. the stand-up-vs-sit-down distinction is now clean.",
        when: "yesterday",
      },
      {
        a: "Houston humidity >70%", b: "Symptom severity baseline",
        was: 0.0, now: 0.55,
        note: "first crossing of the threshold. modest but consistent. august was the giveaway.",
        when: "Saturday",
      },
    ],
    locked: [
      {
        a: "Work email volume", b: "Cognitive load + POTS coupling",
        note: "Your work email isn't connected. We suspect — but can't confirm — that high-email days are eating into your evening recovery.",
        unlock: "Email connection (Pro)",
      },
      {
        a: "Travel days", b: "Multi-day symptom escalation",
        note: "If you connect TripIt, we'll be able to see whether the Thursday Houston→Atlanta trip is the kind of thing that's pulling your weekend down.",
        unlock: "Travel apps (Pro)",
      },
      {
        a: "Continuous BP", b: "POTS pattern resolution",
        note: "Withings BP cuff would let us see the standing-vs-sitting BP delta — the actual POTS signature, not just the proxy.",
        unlock: "Withings BP cuff (Pro)",
      },
    ],
  },

  renee: {
    headline: "247 days of evidence.",
    headlineEm: "Across four diagnoses, three time zones, six specialists.",
    lede: "Your file holds 38,104 indexed signals across 14 input streams. The engine has scored 11,420 pairs and surfaced 312 of statistical significance. The hero pattern below is the one driving Thursday's prediction — a compound of three signals stacking, not one. The library beneath it is everything else, ranked by what's costing you most.",
    indexed: 11420,
    passing: 312,
    newThisWeek: 7,
    driving: 1,
    hero: {
      id: "r-stack",
      headline: "MCAS environment + sleep deficit + cognitive load ≥9d ↔ neurological event within 96h.",
      sub: "Compound r=0.81 across 14 weeks where all three factors stacked. 11 of those 14 weeks ended in an event. The three that didn't: the three where you intervened before Wednesday.",
      r: 0.81,
      n: 14,
      factors: [
        { name: "MCAS-trigger environment", weight: 0.34, r: 0.77, color: "var(--flare)", detail: "Hôtel Beau-Rivage logged Oct 14 · Geneva pollen + cleaning agent confirmed" },
        { name: "Sleep deficit (rolling 7d)", weight: 0.31, r: 0.84, color: "var(--flare)", detail: "−6h12m accumulated since last Wed · architecture compromised" },
        { name: "Cognitive load ≥ 9 days at threshold", weight: 0.35, r: 0.79, color: "var(--warn)", detail: "92/100 · personal threshold 78 · floor: 9 days" },
      ],
      history: [
        { week: "wk-50", outcome: "event" }, { week: "wk-47", outcome: "event" },
        { week: "wk-44", outcome: "near-miss" }, { week: "wk-41", outcome: "event" },
        { week: "wk-38", outcome: "near-miss" }, { week: "wk-35", outcome: "event" },
        { week: "wk-32", outcome: "near-miss" }, { week: "wk-29", outcome: "event" },
        { week: "wk-26", outcome: "event" }, { week: "wk-22", outcome: "event" },
        { week: "wk-18", outcome: "event" }, { week: "wk-14", outcome: "event" },
        { week: "wk-9", outcome: "event" }, { week: "wk-3", outcome: "event" },
      ],
    },
    patterns: [
      {
        id: "r-stack", a: "MCAS env + sleep deficit + cog load ≥9d", b: "Neurological event within 96h",
        r: 0.81, n: 14, domain: "compound", recency: 1.0, novelty: 0.6, driving: true,
        colorA: "var(--flare)", colorB: "var(--ink-9)",
        sparkA: [0.2, 0.3, 0.4, 0.5, 0.6, 0.75, 0.85, 0.92],
        sparkB: [0.1, 0.15, 0.2, 0.3, 0.5, 0.7, 0.85, 0.95],
        note: "the prediction. acted on or it lands.",
        narrative: "The compound your last four crashes had in common. Each individual factor below has its own correlation with bad outcomes — but stacked, they multiply. 14 comparable weeks in your file: 11 ended in a neurological event of severity 6+/10. The 3 clean weeks were the 3 where you broke at least one factor before Wednesday. Geneva is asking for that decision now.",
        timeAxis: ["wk-13", "wk-11", "wk-9", "wk-7", "wk-5", "wk-3", "wk-2", "this wk"],
        moments: [
          { when: "wk-50 (Geneva, last year)", text: "Hôtel Beau-Rivage. Sleep deficit −5h. Cog load 88. Outcome: 5-day relapse.", delta: "event" },
          { when: "wk-32 (Singapore)", text: "Different hotel, similar trigger profile. Sleep deficit −7h. Outcome: 4-day relapse.", delta: "event" },
          { when: "wk-26 (Berlin)", text: "Pre-protocol switched to Hôtel des Bergues equivalent. Sleep made up Tuesday. Outcome: clean.", delta: "near-miss caught" },
          { when: "wk-9 (D.C., 2 weeks ago)", text: "All three factors stacked at home. UN testimony prep. Outcome: 3-day cognitive event.", delta: "event" },
        ],
      },
      {
        id: "r-trans", a: "Transatlantic westbound", b: "MCAS flare within 48h",
        r: 0.77, n: 22, domain: "travel", recency: 0.95, novelty: 0.3, driving: false,
        colorA: "var(--brand-soft)", colorB: "var(--flare)",
        sparkA: [0, 0, 1, 1, 1, 0, 0, 0],
        sparkB: [3.5, 3.0, 5.5, 6.8, 5.5, 4.0, 3.0, 2.5],
        note: "the direction matters. eastbound is half the cost.",
        narrative: "22 westbound transatlantic flights in your file. 17 followed by an MCAS flare within 48h. Cabin pressure differential, dehydration, and circadian disruption stack the same way each time. We have your eastbound at half this rate — your body recovers from the loss-of-time better than the gain.",
        timeAxis: ["−3d", "−2d", "−1d", "flight", "+12h", "+24h", "+48h", "+72h"],
        moments: [
          { when: "October 14 → Geneva", text: "United 950. Lufthansa connection. Dehydration index hit 0.74 mid-flight.", delta: "+5.5/10 by next evening" },
          { when: "August 22 → Frankfurt", text: "First time we ran the in-flight protocol. Severity capped at 4.0.", delta: "−40% vs typical" },
        ],
      },
      {
        id: "r-cog", a: "Cognitive load >9d at threshold", b: "Sleep architecture collapse",
        r: 0.84, n: 18, domain: "cognition", recency: 0.9, novelty: 0.4, driving: false,
        colorA: "var(--warn)", colorB: "var(--flare)",
        sparkA: [70, 75, 80, 85, 88, 90, 91, 92],
        sparkB: [22, 21, 19, 17, 14, 11, 9, 7],
        note: "the leading edge of every relapse. it goes first.",
        narrative: "Your cognitive load index — derived from email response latency, calendar density, SMS volume, and the rolling read on your Oura's 'cognitive recovery' score — has a strong, threshold-shaped relationship with deep-sleep minutes. Below 78/100 there's no relationship. Above 78/100, every additional day adds 1.4 minutes of deep-sleep loss. By day 9, your deep sleep is below the floor needed to clear the inflammatory markers your MCAS specialist watches.",
        timeAxis: ["d-8", "d-7", "d-6", "d-5", "d-4", "d-3", "d-2", "d-1"],
        moments: [
          { when: "wk-9 D.C. (current)", text: "Day 9 above threshold. Deep sleep down to 7 minutes Wednesday. This is the architecture problem your neurologist asked us to flag.", delta: "−15 min deep sleep" },
        ],
      },
      {
        id: "r-sms", a: "SMS volume >200/day", b: "Executive function fatigue (next-day)",
        r: 0.72, n: 67, domain: "behavioral", recency: 0.85, novelty: 0.7, driving: false,
        colorA: "var(--pulse)", colorB: "var(--ink-7)",
        sparkA: [85, 110, 145, 187, 210, 245, 198, 167],
        sparkB: [0.2, 0.3, 0.4, 0.55, 0.7, 0.85, 0.7, 0.5],
        note: "advocacy days have a known price tag now.",
        narrative: "iMessage volume is a proxy for advocacy intensity — and it's a remarkably clean leading indicator of next-day executive function fatigue (decision latency, calendar-error rate, missed-prompt rate). The threshold is sharp at 200 messages. Days above 200 are followed by EF-fatigue scores 35% above your baseline; days below are not.",
        timeAxis: ["d-7", "d-6", "d-5", "d-4", "d-3", "d-2", "d-1", "today"],
        moments: [
          { when: "Tuesday — board crisis", text: "247 messages. Wednesday EF score: 0.85. You missed the 4pm with Dr. Patel. The agent rescheduled.", delta: "+42%" },
        ],
      },
      {
        id: "r-protocol", a: "Pre-flight + pre-event protocol adherence", b: "Near-miss caught (no event)",
        r: 0.88, n: 8, domain: "intervention", recency: 1.0, novelty: 0.6, driving: false,
        colorA: "var(--calm)", colorB: "var(--calm)",
        sparkA: [0, 1, 1, 0, 1, 1, 1, 1],
        sparkB: [0, 1, 1, 0, 1, 1, 1, 1],
        note: "3 caught in the last 8 months. the system works when run.",
        narrative: "When the full pre-protocol runs (vitamin infusion 24–36h before, hotel pre-cleared, second infusion at destination, sleep window protected), 8 of 8 high-risk weeks have ended without an event. The pattern is small-n but startlingly clean. This is the protocol the agent has staged for Geneva.",
        timeAxis: ["wk-23", "wk-19", "wk-15", "wk-13", "wk-10", "wk-7", "wk-5", "wk-2"],
        moments: [
          { when: "wk-7 Berlin — caught", text: "All three factors stacking. Protocol ran cleanly. Outcome: severity capped at 3.5/10. No event.", delta: "near-miss" },
        ],
      },
      {
        id: "r-bp", a: "Barometric drop >12mb (24h)", b: "Same-day MCAS reactivity",
        r: 0.69, n: 41, domain: "environment", recency: 0.7, novelty: 0.4, driving: false,
        colorA: "var(--ink-7)", colorB: "var(--flare)",
        sparkA: [1018, 1015, 1012, 1006, 1002, 998, 1001, 1004],
        sparkB: [2.5, 3.0, 3.8, 5.5, 6.2, 6.0, 5.0, 4.0],
        note: "geneva forecast: −18mb between mon and wed.",
        narrative: "Pulled from your Tomorrow.io integration. Barometric drops above 12mb in a 24h window are followed by elevated histamine response on the same day, lasting roughly 18 hours. This is well-established in MCAS literature — your file confirms it strongly. The Geneva forecast for this week is exactly the kind of drop the pattern flags.",
        timeAxis: ["d-3", "d-2", "d-1", "drop", "+6h", "+12h", "+18h", "+24h"],
        moments: [
          { when: "Last Geneva (Oct)", text: "Barometric dropped 16mb between Sunday and Tuesday. MCAS reactivity scored 6.2/10 by Tuesday afternoon.", delta: "+148%" },
        ],
      },
      {
        id: "r-aria", a: "Aria's recital weeks (her)", b: "Your protected-rest adherence (you)",
        r: 0.74, n: 6, domain: "family", recency: 0.95, novelty: 0.7, driving: false,
        colorA: "var(--pulse)", colorB: "var(--calm)",
        sparkA: [0, 0, 0, 0, 0, 0, 1, 0],
        sparkB: [0.6, 0.5, 0.7, 0.6, 0.55, 0.7, 0.95, 0.8],
        note: "you protect rest harder when something matters. this is fine.",
        narrative: "An emergent pattern from your family calendar. In the 6 weeks where Aria has had a recital, performance, or graduation, your protected-rest adherence climbs to 95% — well above your 64% baseline. The agent now uses this as a predictor for which weeks to defend more aggressively.",
        timeAxis: ["wk-1", "wk-2", "wk-3", "wk-4", "wk-5", "wk-6", "this wk", "wk+1"],
        moments: [
          { when: "Aria's spring recital", text: "You protected Friday + Saturday + Sunday morning. Showed up at 4pm clean.", delta: "no event" },
        ],
      },
      {
        id: "r-thyroid", a: "TSH out of range (last lab)", b: "Cognitive load tolerance ↓",
        r: 0.62, n: 9, domain: "endocrine", recency: 0.5, novelty: 0.3, driving: false,
        colorA: "var(--ink-7)", colorB: "var(--warn)",
        sparkA: [3.2, 3.5, 3.8, 4.1, 4.4, 4.6, 4.2, 3.8],
        sparkB: [82, 80, 78, 76, 73, 71, 75, 79],
        note: "drugs your dose. dr. okafor wants this.",
        narrative: "Pulled from your specialist EHR — TSH readings above 3.5 correlate with a measurably lower cognitive-load threshold (your floor drops from 78 to 73). This means high-load days that would normally be tolerable become triggers during sub-optimally-dosed periods. Last labs were 4.4. Dr. Okafor is reviewing — the agent will surface the recommendation when she replies.",
        timeAxis: ["lab-1", "lab-2", "lab-3", "lab-4", "lab-5", "current", "lab-7", "lab-8"],
        moments: [
          { when: "Lab-4 (April)", text: "TSH 4.4. Same week you missed the Brussels meeting prep deadline.", delta: "−5pt threshold" },
        ],
      },
    ],
    discovery: [
      {
        a: "SMS volume + meeting density (compound)", b: "Same-day deep-sleep loss",
        was: 0.61, now: 0.74,
        note: "a 2-input compound just emerged. the system is finding combinations you wouldn't think to look for.",
        when: "Tuesday",
      },
      {
        a: "Aria's recital weeks", b: "Protected-rest adherence",
        was: 0.0, now: 0.74,
        note: "a tender finding. you defend the weeks that matter to her. we noticed.",
        when: "Wednesday",
      },
      {
        a: "Specialist EHR sync delay", b: "Decision-window collapse",
        was: 0.0, now: 0.58,
        note: "when Dr. Marsh's notes lag >48h, your decisions move forward without them. modest but worth fixing.",
        when: "Friday",
      },
    ],
    locked: [
      {
        a: "Continuous glucose", b: "MCAS-prodrome",
        note: "If you opt into the CGM trial Dr. Okafor proposed in March, we'd be able to test whether glucose volatility is the missing piece in the MCAS prodrome window.",
        unlock: "CGM trial enrollment",
      },
      {
        a: "Voice-stress (calls)", b: "Cognitive load (real-time)",
        note: "If you turned on voice-stress monitoring during board calls, we could give you a real-time floor warning instead of a 9-day-after summary.",
        unlock: "Voice-stress opt-in",
      },
    ],
  },
};

window.PATTERN_LIBRARY = PATTERN_LIBRARY;
