// Three personas — drawn directly from the iMpatient User Archetype Profiles.
// Free / Essential / Pro. The ladder of understanding, not a feature list.
// Voice matches the source document: literary, specific, gentle, true.

const PERSONAS = {
  // FREE TIER — The Observer
  // "I know something is happening. I'm not sure what yet."
  kezia: {
    id: "kezia",
    tier: "Free",
    archetype: "The Observer",
    name: "Harlow",
    age: 31,
    locationStr: "Birmingham, England",
    role: "Secondary school art teacher · newly diagnosed (RRMS, 8 months)",
    blurb: "Not yet committed. 7-day view. The first tool that even seems to speak the same language as the question she's asking.",
    greeting: "Morning, Harlow. Here is what your last seven days",
    greetingEm: "have been telling you.",
    heroLine: "Your watch has been keeping a notebook for you. Here is the first read.",
    lede: "You started keeping a notebook because you wanted something to find what the bad days have in common. Your watch has been keeping a quieter notebook for you. This is the first week we've read it back. Nothing here is a diagnosis. It is just what your body has noticed — and how it lines up with what you have already been writing down.",
    metaLabel: "Free tier · 7-day view",
    metaValue: "Day 6 · 412 signals indexed",
    location: { label: "Birmingham · home", kind: "home", detail: "55°F · light rain", clinical: false },
    weather: {
      current: {
        place: "Birmingham",
        sublabel: "home · 14:22 GMT",
        temp: 55, unit: "°F",
        condition: "Light rain",
        sky: "rain",       // clear | partly | cloudy | rain | storm | snow | night
        pressure: 1006,
        pressureDelta: -4, // mb in last 24h
        pressureTrend: [1014, 1013, 1012, 1010, 1009, 1008, 1007, 1006],
        humidity: 84,
        windMph: 11,
        sunrise: "06:42",
        sunset: "19:18",
      },
      contributing: [
        { label: "Pressure drop", note: "you slept short the last time pressure fell this fast" },
        { label: "Standing forecast", note: "school day · ~5h on feet expected" },
      ],
    },
    inputs: [
      { name: "Apple Watch", on: true, kind: "wearable" },
      { name: "Apple Health", on: true, kind: "health" },
      { name: "Apple Calendar (personal)", on: false, kind: "calendar", note: "Essential" },
      { name: "Outlook (school)", on: false, kind: "calendar", note: "Essential" },
      { name: "Travel apps", on: false, kind: "travel", note: "Pro" },
    ],
    biometrics: [
      { label: "HRV", value: "31", unit: "ms", delta: "low for 11 of last 14 nights", deltaKind: "alert", spark: [42,40,38,36,38,35,33,32,31,33,30,32,31,31], color: "var(--flare)" },
      { label: "Resting HR", value: "74", unit: "bpm", delta: "+6 bpm every Sunday evening", deltaKind: "up", spark: [66,65,67,66,72,68,67,68,73,67,68,69,74,72], color: "var(--warn)" },
      { label: "Sleep", value: "6h 38m", delta: "broken on standing days", deltaKind: "down", spark: [7.5,7.2,6.8,6.4,6.6,6.2,5.9,7.0,6.4,6.1,5.8,6.2,6.4,6.6], color: "var(--warn)" },
      { label: "Time on feet", value: "5h 42m", unit: "/day", delta: "school days run higher", deltaKind: "up", spark: [4.2,5.5,5.8,6.1,5.4,2.1,2.8,4.8,5.6,6.0,5.7,5.9,2.4,5.7], color: "var(--brand)" },
    ],
    scheduleTitle: "Your last seven days · what your body did",
    scheduleSub: "Free tier shows your week in review. Connect your calendar to see what's coming.",
    scheduleMeta: "the shape of one week",
    schedule: [
      { t: "Wed", end: "—", title: "Year 10 critique session · 4h on feet", source: "from your Apple Watch", why: "Standing >5h that day. HRV dropped 8ms that night. You've described the next morning as 'borrowed legs.'", impact: "high" },
      { t: "Thu", end: "—", title: "School play setup · 6h on feet", source: "from your Apple Watch", why: "Worst night of the week followed. Movement next day: lowest in 30d.", impact: "high" },
      { t: "Fri", end: "—", title: "School event · glass of wine, late finish", source: "you noted this in your journal", why: "You wrote: 'wine? event? standing?' Your body says: probably the standing. Wine alone, on rest days, hasn't shown a signature.", impact: "med" },
      { t: "Sat", end: "—", title: "Recovery day at home", source: "from movement + HR", why: "Body's choice, not yours. RHR dropped back toward baseline by evening.", impact: "low" },
      { t: "Sun", end: "—", title: "The pattern your watch found", source: "from your last 4 Sundays", why: "Your resting HR is +6 bpm every Sunday evening. The same time, every week. We can show you what's connected — but we'd need to see your calendar.", impact: "high" },
    ],
    correlations: [
      { a: "Standing >5h", b: "Same-night HRV drop", r: 0.74 },
      { a: "Sunday evening", b: "Resting HR ↑6 bpm", r: 0.91, locked: false, note: "consistent across all 4 Sundays you've worn the watch" },
      { a: "School event nights", b: "Next-day fatigue", r: 0.66 },
      { a: "—", b: "What's behind your Sunday spike?", r: null, locked: true, note: "Connect your calendar to see this" },
    ],
    coachSuggestions: [
      { tag: "Gentle", text: "You already knew you were dreading Mondays. Your body has been logging it for months. That's not weakness — that's data." },
      { tag: "Try this", text: "Next school event: track only one variable. Standing time. We'll show you whether it's the wine or the floor." },
      { tag: "When you're ready", text: "Connecting your calendar would let us show you why your body braces every Sunday evening. No pressure. The 7-day view is yours forever." },
    ],
    behavioral: [
      { label: "Days on feet >5h", value: "4", unit: "/7d", delta: "all 4 followed by a hard night", deltaKind: "up" },
      { label: "Notebook entries", value: "9", unit: "/14d", delta: "the days you wrote about", deltaKind: "down" },
      { label: "Apps you've tried", value: "3", delta: "this is the third", deltaKind: "down" },
    ],
  },

  // ESSENTIAL — The Manager
  // "I know what I have. I'm learning how to live alongside it."
  simone: {
    id: "simone",
    tier: "Essential",
    archetype: "The Manager",
    name: "Bella",
    age: 38,
    locationStr: "Houston, Texas",
    role: "Marketing director · single mum of 3 · endometriosis + POTS",
    blurb: "Past the diagnosis. Has the spreadsheet. Needs the system to see the bad week before it arrives.",
    greeting: "Morning, Bella. The week you've been bracing for",
    greetingEm: "is the one I'm seeing too.",
    heroLine: "Your spreadsheet has been right for four years. Now it can see forward.",
    lede: "Your spreadsheet has been right for four years. It just couldn't see forward. Today is Tuesday of a campaign-launch week — you have meetings stacked from 9 to 5 every day through Friday — and your body has already started doing what it does in this kind of week. You don't have to wait to be broken by it. Here's what we can move.",
    metaLabel: "Essential · work calendar connected",
    metaValue: "Day 184 · 11,420 signals indexed",
    location: { label: "Houston · MD Anderson · 0.3mi", kind: "clinical", detail: "Imani's pediatric oncology follow-up · 14:00", clinical: true, who: "Imani (daughter, 13)" },
    weather: {
      current: {
        place: "Houston",
        sublabel: "MD Anderson · 13:48 CT",
        temp: 78, unit: "°F",
        condition: "Hot · humid",
        sky: "partly",
        pressure: 1018,
        pressureDelta: 0,
        pressureTrend: [1017, 1018, 1018, 1018, 1018, 1018, 1018, 1018],
        humidity: 71,
        windMph: 6,
        sunrise: "07:12",
        sunset: "19:34",
      },
      contributing: [
        { label: "Heat + humidity", note: "POTS-relevant — your last 4 high-humidity days each cost an HRV step" },
        { label: "Pressure stable", note: "no environmental load on top of the meeting block" },
      ],
    },
    inputs: [
      { name: "Oura Ring", on: true, kind: "wearable" },
      { name: "Apple Health", on: true, kind: "health" },
      { name: "Google Calendar (work)", on: true, kind: "calendar" },
      { name: "iCloud Calendar (family)", on: true, kind: "calendar" },
      { name: "Cycle tracker", on: true, kind: "health" },
      { name: "Work Email", on: false, kind: "email", note: "Pro" },
      { name: "Travel apps", on: false, kind: "travel", note: "Pro" },
      { name: "Withings BP cuff", on: false, kind: "wearable", note: "Pro" },
    ],
    biometrics: [
      { label: "HRV", value: "34", unit: "ms", delta: "−11ms vs your launch-week baseline", deltaKind: "alert", spark: [48,46,45,43,42,40,39,38,37,36,35,35,34,34], color: "var(--flare)" },
      { label: "Resting HR", value: "78", unit: "bpm", delta: "+8 bpm · POTS pattern emerging", deltaKind: "up", spark: [70,70,71,72,72,73,74,75,76,76,77,77,78,78], color: "var(--warn)" },
      { label: "Sleep", value: "5h 54m", delta: "Imani's been doing the dishes again", deltaKind: "alert", spark: [7.0,6.8,6.6,6.5,6.4,6.2,6.0,5.9,5.8,5.9,5.8,5.7,5.9,5.9], color: "var(--warn)" },
      { label: "Standing time", value: "6h 12m", unit: "/day", delta: "above your POTS threshold (5h)", deltaKind: "up", spark: [4.5,4.8,5.0,5.2,5.5,5.8,6.0,6.0,6.1,6.0,6.1,6.2,6.1,6.2], color: "var(--warn)" },
    ],
    scheduleTitle: "Your day · Tuesday, campaign-launch week",
    scheduleSub: "from your work calendar + cycle tracker · weighted against the last 4 launch weeks",
    scheduleMeta: "8.5h of meetings · 6h+ standing predicted",
    schedule: [
      { t: "07:30", end: "08:30", title: "Imani off to school · Khalil to daycare", source: "Family rhythm", why: "Mornings are your strongest window. Body knows it.", impact: "low" },
      { t: "09:00", end: "12:00", title: "Campaign creative review · 3 stand-ups", source: "Work Calendar", why: "Three rooms, three walks between. POTS-relevant standing time logged here.", impact: "high" },
      { t: "12:00", end: "12:30", title: "Lunch · suggested horizontal break", source: "iMpatient suggested · you accepted last week", why: "30min horizontal at noon dropped your afternoon HR by 6bpm last launch week. Same protocol available.", impact: "low" },
      { t: "13:00", end: "17:00", title: "Stakeholder presentations · 4 back-to-back", source: "Work Calendar", why: "This is the block that ate you alive last November. Same shape. Different week. Your body remembers.", impact: "high" },
      { t: "17:30", end: "18:30", title: "Pickup chain · 3 schools, 3 kids", source: "Family Calendar", why: "Standing transitions. After-meeting cortisol still elevated. Add: extra hydration in the car.", impact: "med" },
      { t: "19:30", end: "21:00", title: "Dinner + homework + bedtime", source: "Family rhythm", why: "Imani has been picking up the slack. You've noticed. We've noticed too.", impact: "med" },
    ],
    correlations: [
      { a: "Daily meetings >6h", b: "POTS symptoms within 48h", r: 0.84, hero: true, note: "the correlation you chased in your spreadsheet for 4 years" },
      { a: "Cycle day 24–28", b: "Symptom severity ↑", r: 0.78 },
      { a: "Standing >5h", b: "Next-morning HRV drop", r: 0.71 },
      { a: "Late campaign weeks", b: "Imani's increased chore load", r: 0.69, note: "your daughter is a leading indicator" },
      { a: "Pre-hydration protocol", b: "Crash avoided", r: 0.82, note: "your evidence, your protocol" },
    ],
    coachSuggestions: [
      { tag: "Move", text: "Block 12:00–12:30 horizontal today. Same protocol that worked last launch week. I've drafted the calendar hold." },
      { tag: "Reduce", text: "The 16:00 slot can become a walking 1:1 outdoors instead of conference room — same conversation, half the standing." },
      { tag: "For Imani", text: "You have not asked, but: this is a 6/10 week, not an 8/10 week. She does not need to be doing the dishes. I can draft a note." },
    ],
    behavioral: [
      { label: "Meeting hours today", value: "8.5", unit: "h", delta: "+38% vs non-launch weeks", deltaKind: "up" },
      { label: "Days since last collapse", value: "184", delta: "your record", deltaKind: "down" },
      { label: "Spreadsheet rows replaced", value: "1,847", delta: "you don't need it anymore", deltaKind: "down" },
    ],
  },

  // PRO — The Complex Human
  // "My body, my family, my career. All at once. Every day."
  renee: {
    id: "renee",
    tier: "Pro",
    archetype: "The Complex Human",
    name: "Grayson",
    age: 47,
    locationStr: "Washington D.C. → Geneva (Tuesday)",
    role: "Nonprofit CEO · 4 kids · RRMS · MCAS · ADHD · hypothyroidism",
    blurb: "Has crashed four times in two years. Each time she said: I could see this coming. Now she actually can.",
    greeting: "Grayson — Sunday evening read.",
    greetingEm: "Thursday is asking for a decision.",
    heroLine: "Thursday carries an 81% probability of a neurological event. You have time.",
    lede: "Across the indexed history of your last 14 comparable weeks, Thursday carries an 81% probability of a significant neurological event if no adjustments are made. Three factors are stacking: the Tuesday hotel in Geneva is MCAS-sensitive (you reacted there in October), a sleep deficit has been accumulating since last Wednesday, and your cognitive load index has been above your personal threshold for nine consecutive days. This is the prediction window. You have time.",
    metaLabel: "Pro · all three domains · agentic",
    metaValue: "Day 247 · 38,104 signals indexed",
    location: { label: "Washington D.C. · home → Geneva (Tue 06:30)", kind: "home", detail: "1014mb · 52°F · clear · Geneva forecast: 996mb · 41°F · rain", clinical: false },
    weather: {
      current: {
        place: "Washington D.C.",
        sublabel: "home · 18:14 ET",
        temp: 52, unit: "°F",
        condition: "Clear",
        sky: "clear",
        pressure: 1014,
        pressureDelta: +1,
        pressureTrend: [1011, 1012, 1012, 1013, 1013, 1014, 1014, 1014],
        humidity: 48,
        windMph: 7,
        sunrise: "06:24",
        sunset: "19:42",
      },
      destination: {
        place: "Geneva",
        sublabel: "Tue 14:30 CET · 36h from now",
        temp: 41, unit: "°F",
        condition: "Rain · low ceiling",
        sky: "rain",
        pressure: 996,
        pressureDelta: -18, // vs origin
        pressureTrend: [1014, 1011, 1008, 1005, 1003, 1001, 998, 996],
        humidity: 92,
        windMph: 14,
        sunrise: "06:48",
        sunset: "20:14",
        flight: { code: "LH441", depart: "Tue 06:30", duration: "8h 20m" },
      },
      contributing: [
        { label: "−18mb pressure drop", note: "your MCAS threshold is −12mb · this trip clears it by 50%", weight: "high" },
        { label: "−11°C arrival", note: "raynaud's risk pre-loaded · pre-warming protocol queued", weight: "med" },
        { label: "92% humidity Geneva", note: "cabin → cold-rain transition is the trigger pattern" },
      ],
    },
    inputs: [
      { name: "Oura Ring", on: true, kind: "wearable" },
      { name: "Apple Watch Ultra", on: true, kind: "wearable" },
      { name: "Withings BP + Body+", on: true, kind: "wearable" },
      { name: "Apple Health", on: true, kind: "health" },
      { name: "Outlook (work)", on: true, kind: "calendar" },
      { name: "Google Calendar (board)", on: true, kind: "calendar" },
      { name: "iCloud (family)", on: true, kind: "calendar" },
      { name: "Care-team calendar", on: true, kind: "calendar" },
      { name: "Gmail + Outlook", on: true, kind: "email" },
      { name: "TripIt + United + Lufthansa + UA Club", on: true, kind: "travel" },
      { name: "Climate + barometric (Tomorrow.io)", on: true, kind: "travel" },
      { name: "iMessage / SMS volume", on: true, kind: "behavioral" },
      { name: "Specialist EHR (×6)", on: true, kind: "care" },
      { name: "Service dog vet portal", on: true, kind: "care" },
    ],
    biometrics: [
      { label: "HRV", value: "26", unit: "ms", delta: "−16ms · approaching your relapse threshold", deltaKind: "alert", spark: [42,41,40,38,37,35,34,32,31,30,29,28,27,26], color: "var(--flare)" },
      { label: "Resting HR", value: "84", unit: "bpm", delta: "+13 bpm · MCAS pre-flare signature", deltaKind: "alert", spark: [71,72,73,74,75,76,77,78,79,80,81,82,83,84], color: "var(--flare)" },
      { label: "Sleep deficit", value: "6h 12m", delta: "accumulated since Wed · the body is keeping score", deltaKind: "alert", spark: [0,-0.5,-1.0,-1.8,-2.4,-3.1,-3.9,-4.4,-4.9,-5.3,-5.6,-5.9,-6.0,-6.2], color: "var(--flare)" },
      { label: "Cognitive load", value: "92", unit: "/100", delta: "9 days above personal threshold (78)", deltaKind: "alert", spark: [70,72,75,78,80,82,84,86,88,89,90,91,91,92], color: "var(--flare)" },
    ],
    scheduleTitle: "This week · Geneva block + UN testimony",
    scheduleSub: "from work, family, travel, specialist calendars · agent has flagged 3 changes available",
    scheduleMeta: "5 countries · 14 meetings · Thursday is the pinch",
    schedule: [
      { t: "Mon", end: "—", title: "D.C. → flight Tue 06:30", source: "TripIt + Work Calendar", why: "Last 4 transatlantic departures: HRV dropped 9ms by arrival. We've pre-loaded the recovery protocol.", impact: "med" },
      { t: "Tue", end: "—", title: "Geneva · Hôtel Beau-Rivage", source: "Travel · auto-flagged by agent", why: "MCAS reaction logged here Oct 14. Three alternative properties cleared by your environmental profile. One is held provisionally.", impact: "high" },
      { t: "Wed", end: "—", title: "Pre-testimony briefings · 9 hours of meetings", source: "Work Calendar + 3 country offices", why: "Cognitive load already at 92/100. Each additional hour beyond hour 6 doubles next-day risk.", impact: "high" },
      { t: "Thu 11:00", end: "13:00", title: "UN testimony · this is the one", source: "Work Calendar · cannot move", why: "The morning is non-negotiable. The afternoon is where adjustments live.", impact: "high" },
      { t: "Thu 14:00", end: "18:00", title: "Closed-door follow-ups", source: "Work Calendar · agent recommends decline", why: "If Thursday morning happens cleanly, the afternoon is where the crash lands. Your team can hold these. Philippa is briefed.", impact: "high" },
      { t: "Fri", end: "—", title: "Rest day · already protected", source: "Family Calendar · Philippa has the children", why: "She did not need to be asked. She saw the same shape you did.", impact: "low" },
      { t: "Sat", end: "—", title: "Aria's recital · 4pm", source: "Family Calendar", why: "Eight years old. She does not know about the prediction. She does not need to. You will be there.", impact: "low" },
    ],
    correlations: [
      { a: "MCAS-trigger hotel + sleep deficit + cog load >9d", b: "Neurological event within 96h", r: 0.81, hero: true, note: "the prediction. 14 comparable weeks. acted on or it will land." },
      { a: "Transatlantic westbound", b: "MCAS flare within 48h", r: 0.77 },
      { a: "Cognitive load >9 days at threshold", b: "Sleep architecture collapse", r: 0.84 },
      { a: "SMS volume >200/day", b: "Executive function fatigue", r: 0.72 },
      { a: "Pre-protocol adherence", b: "Near-miss caught", r: 0.88, note: "3 caught in last 8 months" },
    ],
    coachSuggestions: [
      { tag: "Agent · ready to send", text: "Switch hotel to Hôtel des Bergues — environmentally cleared, 4-min walk from UN venue. Your assistant is cc'd. Awaiting your one-tap approval." },
      { tag: "Pre-flight protocol", text: "Geneva is +18mb barometric vs D.C. and 11°C colder. Vitamin infusion scheduled tomorrow 14:00 (Dr. Marsh's clinic, confirmed). Second infusion booked Geneva, Wed 16:00. Compression socks packed (checklist sent to Philippa). Prescription supply audited: 14-day window covered + 3-day buffer." },
      { tag: "Agent · ready to send", text: "Decline the four Thursday afternoon follow-ups. I've drafted the message in your voice — gracious, specific, opens Friday morning instead. Awaiting approval." },
      { tag: "Travel watch", text: "Lufthansa LH441 currently on time. If delay >90min, I'll re-time the Geneva infusion automatically and alert the clinic. You don't need to think about it." },
      { tag: "For Philippa", text: "I've sent her the Friday hold. She replied: 'On it. The kids and I have a plan.' Aria's recital locked with a 2h pre-rest block." },
      { tag: "For your neurologist", text: "This week's signal trace + the prediction is queued for Dr. Marsh. Send before Thursday or hold for Monday's 4pm review?" },
    ],
    behavioral: [
      { label: "Active diagnoses", value: "4", delta: "indexed simultaneously", deltaKind: "down" },
      { label: "Specialists coordinated", value: "6", delta: "across 3 cities · they don't talk · I do", deltaKind: "down" },
      { label: "Crashes prevented", value: "3", delta: "in last 8 months · 0 full relapses", deltaKind: "down" },
      { label: "SMS volume today", value: "187", unit: "msgs", delta: "high-advocacy day", deltaKind: "up" },
      { label: "Cognitive load (9d avg)", value: "87", unit: "/100", delta: "above personal threshold", deltaKind: "alert" },
      { label: "Days since full relapse", value: "247", delta: "since you started using me", deltaKind: "down" },
    ],
  },
};

window.PERSONAS = PERSONAS;
